diff --git a/node_modules/ref-struct-napi/node_modules/ref-napi/lib/ref.js b/node_modules/ref-struct-napi/node_modules/ref-napi/lib/ref.js
index 253f0bd..2bb745e 100644
--- a/node_modules/ref-struct-napi/node_modules/ref-napi/lib/ref.js
+++ b/node_modules/ref-struct-napi/node_modules/ref-napi/lib/ref.js
@@ -740,7 +740,18 @@ exports._writePointer = exports.writePointer;
 
 exports.writePointer = function writePointer (buf, offset, ptr) {
   debug('writing pointer to buffer', buf, offset, ptr);
-  exports._writePointer(buf, offset, ptr);
+  /**
+   * TODO: Find out the cause of "Maximum call stack size exceeded" exception
+   * In this patch, we will ignore this exception
+   * What we know so far:
+   * - The exception happens AFTER jest has finished running the tests, not during
+   * - So far, catching the exception does not cause any issue
+   */
+  try {
+    exports._writePointer(buf, offset, ptr);
+  } catch(e) {
+    if(e.message !== 'Maximum call stack size exceeded') throw e;
+  }
   exports._attach(buf, ptr);
 };
 
